/** @type {import('prettier').Config} */
module.exports = {
	plugins: [
		'@ianvs/prettier-plugin-sort-imports',
		'prettier-plugin-packagejson',
		'prettier-plugin-jsdoc',
		'prettier-plugin-curly',
		'prettier-plugin-tailwindcss',
	],
	endOfLine: 'lf',
	semi: true,
	singleQuote: true,
	useTabs: true,
	tabWidth: 2,
	printWidth: 80,
	trailingComma: 'es5',

	tailwindFunctions: ['clsx', 'cn', 'cva', 'tv'],

	importOrder: [
		'^@/env.mjs',
		'',
		'^(react/(.*)$)|^(react$)',
		'^(next/(.*)$)|^(next$)',
		'<THIRD_PARTY_MODULES>',
		'^types$',
		'',
		'^@prisma/(.*)$',
		'@/db/prisma(.*)$',
		'^@/db/(.*)$',
		'',
		'^@/quranapi/(.*)$',
		'',
		'^@/stores/(.*)$',
		'',
		'',
		'^@/lib/(.*)$',
		'',
		'^@/components/(.*)$',
		'',
		'^@/styles/(.*)$',
		'',
		'^@/(.*)$',
		'',
		'^[./]',
		'',
		'.s?css$',
		'',
		'.(jpg|png)$',
	],
	// importOrderSeparation: false,
	// importOrderSortSpecifiers: true,
	// importOrderBuiltinModulesToTop: true,
	importOrderParserPlugins: ['typescript', 'jsx', 'decorators-legacy'],
	// importOrderMergeDuplicateImports: true,
	// importOrderCombineTypeAndValueImports: true,
};
